# Generated by Django 6.1.1 on 2026-09-29 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('user_full_name', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('Login', 'Login'), ('Logout', 'Logout'), ('Profile Updated', 'Profile Updated'), ('Password Changed', 'Password Changed'), ('Role Changed', 'Role Changed'), ('Permission Updated', 'Permission Updated'), ('User Created', 'User Created'), ('User Activated', 'User Activated'), ('User Deactivated', 'User Deactivated'), ('User Deleted', 'User Deleted'), ('Role Created', 'Role Created'), ('Role Deleted', 'Role Deleted')], max_length=50)),
                ('description', models.TextField()),
                ('module', models.CharField(default='User Management', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='Success', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
