# Generated by Django 6.1.1 on 2026-09-30 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_supplier_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('account_title', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=100)),
                ('iban', models.CharField(blank=True, default='', max_length=100)),
                ('branch_name', models.CharField(blank=True, default='', max_length=255)),
                ('branch_code', models.CharField(blank=True, default='', max_length=50)),
                ('swift_code', models.CharField(blank=True, default='', max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='factory.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Bank Account',
                'verbose_name_plural': 'Supplier Bank Accounts',
                'ordering': ['-is_primary', 'bank_name'],
            },
        ),
    ]
