# Generated by Django 6.1.1 on 2026-09-30 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0005_loom_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beam_code', models.CharField(max_length=50, unique=True)),
                ('beam_name', models.CharField(blank=True, default='', max_length=255)),
                ('beam_number', models.CharField(max_length=100, unique=True)),
                ('yarn_count', models.CharField(blank=True, default='', max_length=100)),
                ('warp_count', models.PositiveIntegerField(blank=True, null=True)),
                ('total_ends', models.PositiveIntegerField(blank=True, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('production_order', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sizing', 'Sizing'), ('Loaded', 'Loaded'), ('In Production', 'In Production'), ('Completed', 'Completed'), ('Damaged', 'Damaged'), ('Inactive', 'Inactive')], default='Available', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_beams', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_beams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Beam',
                'verbose_name_plural': 'Beams',
                'ordering': ['beam_code'],
            },
        ),
    ]
