# Generated by Django 6.1.1 on 2026-10-01 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0006_beam_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YarnBuyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('phone_no', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='Pakistan', max_length=100)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_yarn_buyers', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_yarn_buyers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yarn Buyer',
                'verbose_name_plural': 'Yarn Buyers',
                'ordering': ['buyer_name'],
            },
        ),
        migrations.CreateModel(
            name='YarnIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yarn_name', models.CharField(max_length=255)),
                ('yarn_type', models.CharField(max_length=100)),
                ('yarn_count', models.CharField(max_length=100)),
                ('set_no', models.CharField(help_text='Manually entered set number. Not auto-generated.', max_length=100)),
                ('intake_date', models.DateField()),
                ('production_type', models.CharField(blank=True, default='', max_length=100)),
                ('bags', models.PositiveIntegerField(default=0)),
                ('cones_per_bag', models.PositiveIntegerField(default=0)),
                ('rate_per_bag', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('weight_per_bag_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_cones', models.PositiveIntegerField(default=0)),
                ('total_rate', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_weight_kg', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('net_weight_lb', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('outcome_bags', models.PositiveIntegerField(default=0)),
                ('outcome_weight_kg', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('outcome_weight_lb', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('remaining_bags', models.PositiveIntegerField(default=0)),
                ('remaining_weight_kg', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('remaining_weight_lb', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_yarn_intakes', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='yarn_intakes', to='factory.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_yarn_intakes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yarn Intake',
                'verbose_name_plural': 'Yarn Intakes',
                'ordering': ['-intake_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='YarnOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_type', models.CharField(choices=[('Sizing', 'Sizing'), ('Weft', 'Weft'), ('Sold', 'Sold')], default='Sizing', max_length=20)),
                ('outcome_bags', models.PositiveIntegerField(default=0)),
                ('outcome_cones_per_bag', models.PositiveIntegerField(default=0)),
                ('outcome_weight_per_bag_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('outcome_weight_kg', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('outcome_weight_lb', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('outcome_date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_yarn_outcomes', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_yarn_outcomes', to=settings.AUTH_USER_MODEL)),
                ('yarn_buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='yarn_outcomes', to='factory.yarnbuyer')),
                ('yarn_intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='factory.yarnintake')),
            ],
            options={
                'verbose_name': 'Yarn Outcome',
                'verbose_name_plural': 'Yarn Outcomes',
                'ordering': ['-outcome_date', '-id'],
            },
        ),
    ]
