# Generated by Django 6.1.1 on 2026-10-03 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0008_add_sizing_model_and_yarnoutcome_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SizingOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_date', models.DateField()),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sizing_outcomes', to=settings.AUTH_USER_MODEL)),
                ('sizing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outcomes', to='factory.sizing')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sizing_outcomes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sizing Outcome',
                'verbose_name_plural': 'Sizing Outcomes',
                'ordering': ['-outcome_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SizingBeamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_USE', 'In Use'), ('COMPLETED', 'Completed'), ('RELEASED', 'Released')], default='ASSIGNED', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sizing_assignments', to='factory.beam')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sizing_beam_assignments', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sizing_beam_assignments', to=settings.AUTH_USER_MODEL)),
                ('sizing_outcome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beam_assignments', to='factory.sizingoutcome')),
            ],
            options={
                'verbose_name': 'Sizing Beam Assignment',
                'verbose_name_plural': 'Sizing Beam Assignments',
                'ordering': ['-assigned_at', '-id'],
                'indexes': [models.Index(fields=['beam', 'status'], name='factory_sba_beam_stat_idx'), models.Index(fields=['sizing_outcome', 'status'], name='factory_sba_so_stat_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['ASSIGNED', 'IN_USE'])), fields=('beam',), name='unique_active_sizing_assignment_per_beam')],
            },
        ),
    ]
