# Generated by Django 6.1.1 on 2026-10-03 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0009_sizingoutcome_sizingbeamassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sizingoutcome',
            name='back_beam',
            field=models.CharField(blank=True, default='', help_text='Back beam count / identifier', max_length=100),
        ),
        migrations.AddField(
            model_name='sizingoutcome',
            name='bag_packing_cone',
            field=models.PositiveIntegerField(default=0, help_text='Packing cones per bag'),
        ),
        migrations.AddField(
            model_name='sizingoutcome',
            name='brand',
            field=models.CharField(blank=True, default='', help_text='Yarn Brand / Mill', max_length=150),
        ),
        migrations.AddField(
            model_name='sizingoutcome',
            name='count',
            field=models.CharField(blank=True, default='', help_text='Yarn Count (e.g. 20/1, 40/1)', max_length=100),
        ),
        migrations.AddField(
            model_name='sizingoutcome',
            name='lagat_bags',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Lagat in bags', max_digits=12),
        ),
        migrations.AddField(
            model_name='sizingoutcome',
            name='lagat_cones',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Lagat in cones', max_digits=12),
        ),
        migrations.AddField(
            model_name='sizingoutcome',
            name='remaining_bags_on_sizing_stock',
            field=models.PositiveIntegerField(default=0, help_text='Remaining bags on sizing stock'),
        ),
        migrations.AddField(
            model_name='sizingoutcome',
            name='remaining_cones_on_sizing_stock',
            field=models.PositiveIntegerField(default=0, help_text='Remaining cones on sizing stock'),
        ),
        migrations.AddField(
            model_name='sizingoutcome',
            name='set_length_gaz',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Set length in gaz (yards)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sizingoutcome',
            name='set_length_meter',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Set length in meters', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sizingoutcome',
            name='set_no',
            field=models.CharField(blank=True, default='', help_text='Sizing Set Number', max_length=100),
        ),
        migrations.AddField(
            model_name='sizingoutcome',
            name='sizing_name',
            field=models.CharField(blank=True, default='', help_text='Name of the Sizing Unit', max_length=255),
        ),
        migrations.AddField(
            model_name='sizingoutcome',
            name='total_bags_on_sizing',
            field=models.PositiveIntegerField(default=0, help_text='Total bags sent/processed on sizing'),
        ),
        migrations.AddField(
            model_name='sizingoutcome',
            name='total_cones',
            field=models.PositiveIntegerField(default=0, help_text='Total cones on sizing'),
        ),
        migrations.AddField(
            model_name='sizingoutcome',
            name='total_set_lumbai',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total set length / lumbai', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sizingoutcome',
            name='total_set_shortage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total set shortage', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sizingoutcome',
            name='total_tarr',
            field=models.PositiveIntegerField(blank=True, help_text='Total ends / Tarr count', null=True),
        ),
        migrations.AddField(
            model_name='sizingoutcome',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fabric / Reed width in inches', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sizingoutcome',
            name='yarn_beam',
            field=models.CharField(blank=True, default='', help_text='Yarn beam count / identifier', max_length=100),
        ),
        migrations.CreateModel(
            name='BeamLoading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warp_count', models.CharField(blank=True, default='', help_text='Warp yarn count', max_length=100)),
                ('weft_count', models.CharField(blank=True, default='', help_text='Weft yarn count', max_length=100)),
                ('reed_width', models.DecimalField(blank=True, decimal_places=2, help_text='Reed width in inches', max_digits=10, null=True)),
                ('pick', models.DecimalField(blank=True, decimal_places=2, help_text='Pick / PPI', max_digits=10, null=True)),
                ('reed_count', models.DecimalField(blank=True, decimal_places=2, help_text='Reed count', max_digits=10, null=True)),
                ('pick_count', models.DecimalField(blank=True, decimal_places=2, help_text='Pick count', max_digits=10, null=True)),
                ('shortage', models.DecimalField(blank=True, decimal_places=2, help_text='Expected / observed shortage', max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, help_text='Fabric width in inches', max_digits=10, null=True)),
                ('lakhai', models.DecimalField(blank=True, decimal_places=2, help_text='Lakhai (drawing-in / drafting cost or measurement)', max_digits=10, null=True)),
                ('installation_date', models.DateField(blank=True, help_text='Date beam was installed on loom', null=True)),
                ('status', models.CharField(choices=[('Loaded', 'Loaded'), ('In Production', 'In Production'), ('Completed', 'Completed'), ('Empty', 'Empty')], default='Loaded', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loadings', to='factory.beam')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_beam_loadings', to=settings.AUTH_USER_MODEL)),
                ('loom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beam_loadings', to='factory.loom')),
                ('sizing_outcome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beam_loadings', to='factory.sizingoutcome')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_beam_loadings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Beam Loading',
                'verbose_name_plural': 'Beam Loadings',
                'ordering': ['-installation_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField(help_text='Date of production entry')),
                ('shift', models.CharField(blank=True, default='General', help_text='Production shift (e.g. Morning, Night, General)', max_length=50)),
                ('meters_produced', models.DecimalField(decimal_places=2, default=0, help_text='Fabric length produced in meters', max_digits=12)),
                ('operator_name', models.CharField(blank=True, default='', help_text='Loom master / weaver operator name', max_length=150)),
                ('remarks', models.TextField(blank=True, default='')),
                ('beam_emptied', models.BooleanField(default=False, help_text='Set to True when the physical beam is finished/empty')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productions', to='factory.beam')),
                ('beam_loading', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productions', to='factory.beamloading')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_productions', to=settings.AUTH_USER_MODEL)),
                ('loom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productions', to='factory.loom')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_productions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Production',
                'verbose_name_plural': 'Productions',
                'ordering': ['-production_date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='beamloading',
            index=models.Index(fields=['beam', 'status'], name='factory_bl_beam_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='beamloading',
            index=models.Index(fields=['loom', 'status'], name='factory_bl_loom_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='beamloading',
            index=models.Index(fields=['sizing_outcome', 'status'], name='factory_bl_so_stat_idx'),
        ),
        migrations.AddConstraint(
            model_name='beamloading',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['Loaded', 'In Production'])), fields=('beam',), name='unique_active_loading_per_beam'),
        ),
        migrations.AddConstraint(
            model_name='beamloading',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['Loaded', 'In Production'])), fields=('loom',), name='unique_active_loading_per_loom'),
        ),
    ]
