# Generated by Django 5.0.14 on 2026-10-03 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("factory", "0010_sizingoutcome_back_beam_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loom",
            name="loom_type",
        ),
        migrations.RemoveField(
            model_name="loom",
            name="manufacturer",
        ),
        migrations.RemoveField(
            model_name="loom",
            name="serial_number",
        ),
    ]
