# Generated by Django 5.0.14 on 2026-10-03 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("factory", "0011_remove_loom_loom_type_remove_loom_manufacturer_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="beam",
            options={
                "ordering": ["beam_number"],
                "verbose_name": "Beam",
                "verbose_name_plural": "Beams",
            },
        ),
        migrations.RemoveField(
            model_name="beam",
            name="beam_code",
        ),
    ]
