# Generated by Django 6.1.1 on 2026-10-04 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0012_alter_beam_options_remove_beam_beam_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sizingbeamassignment',
            name='factory_sba_so_stat_idx',
        ),
        migrations.AddField(
            model_name='sizingbeamassignment',
            name='yarn_outcome',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='beam_assignments', to='factory.yarnoutcome'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='sizingbeamassignment',
            index=models.Index(fields=['yarn_outcome', 'status'], name='factory_sba_yo_stat_idx'),
        ),
        migrations.RemoveField(
            model_name='sizingbeamassignment',
            name='sizing_outcome',
        ),
    ]
