# Generated by Django 6.1.1 on 2026-10-04 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0013_remove_sizingbeamassignment_factory_sba_so_stat_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sizingbeamassignment',
            name='unique_active_sizing_assignment_per_beam',
        ),
        migrations.AlterField(
            model_name='sizingbeamassignment',
            name='beam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sizing_assignments', to='factory.beam'),
        ),
        migrations.AddConstraint(
            model_name='sizingbeamassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['ASSIGNED', 'IN_USE']), ('beam__isnull', False)), fields=('beam',), name='unique_active_sizing_assignment_per_beam'),
        ),
    ]
