# Generated by Django 6.1.1 on 2026-10-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0014_remove_sizingbeamassignment_unique_active_sizing_assignment_per_beam_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sizingbeamassignment',
            name='unique_active_sizing_assignment_per_beam',
        ),
        migrations.RemoveIndex(
            model_name='sizingbeamassignment',
            name='factory_sba_beam_stat_idx',
        ),
        migrations.RemoveField(
            model_name='sizingbeamassignment',
            name='beam',
        ),
        migrations.AddField(
            model_name='sizingbeamassignment',
            name='beam',
            field=models.ManyToManyField(blank=True, related_name='sizing_assignments', to='factory.beam'),
        ),
    ]
