# Generated by Django 6.1.1 on 2026-10-04 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0015_remove_sizingbeamassignment_unique_active_sizing_assignment_per_beam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizingoutcome',
            name='sizing',
        ),
        migrations.AddField(
            model_name='sizingoutcome',
            name='set_bill',
            field=models.CharField(blank=True, default='', help_text='Set bill / invoice number', max_length=100),
        ),
        migrations.AddField(
            model_name='sizingoutcome',
            name='yarn_outcome',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sizing_outcomes', to='factory.yarnoutcome'),
            preserve_default=False,
        ),
    ]
