# Generated by Django 5.0.14 on 2026-10-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factory", "0016_remove_sizingoutcome_sizing_sizingoutcome_set_bill_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sizingbeamassignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("ASSIGNED", "Assigned"),
                    ("IN_USE", "In Use"),
                    ("RECEIVED", "Received"),
                    ("COMPLETED", "Completed"),
                    ("RELEASED", "Released"),
                ],
                default="ASSIGNED",
                max_length=20,
            ),
        ),
    ]
