# Generated by Django 5.0.14 on 2026-10-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factory", "0017_alter_sizingbeamassignment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="sizingoutcome",
            name="net_weight_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Net weight in KG",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sizingoutcome",
            name="rate_per_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Rate per KG for sizing",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sizingoutcome",
            name="total_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total rate of net weight (net_weight_kg * rate_per_kg)",
                max_digits=15,
                null=True,
            ),
        ),
    ]
