# Generated by Django 5.0.14 on 2026-10-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factory", "0018_sizingoutcome_net_weight_kg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="yarnoutcome",
            name="status",
            field=models.CharField(
                choices=[
                    ("In Sizing", "In Sizing"),
                    ("Received", "Received"),
                    ("Dispatched", "Dispatched"),
                    ("Completed", "Completed"),
                ],
                default="In Sizing",
                max_length=30,
            ),
        ),
    ]
