# Generated by Django 5.0.14 on 2026-10-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factory", "0019_yarnoutcome_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="sizingbeamassignment",
            name="beam_yarn_length",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
